language: ruby
jdk:
  - oraclejdk8
sudo: false
rvm:
  - 2.3.1
before_install:
  - openssl aes-256-cbc -K $encrypted_a8e0f02164d0_key -iv $encrypted_a8e0f02164d0_iv -in etc/deploy -out ../deploy -d
  - chmod 600 ../deploy
  - eval `ssh-agent -s` && ssh-add ../deploy
install:
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
script: buildr clean package site:deploy publish_if_tagged
git:
  depth: 10
env:
  global:
    - secure: "GOdeMpxds3cyvmG+5vawRitdsUU6f0KV8XYCzX4f8GNDCcr3JflsbZUkjKx+8uVtxpqqzJ+9b407/PKiXLtv/zNVsLjl9lmyuav/SVvLM/avMbH32eiEWscG8xSnxbdOEKTTOTN6RtmOki9ERhI3b3DmIXngdAgNObrPlpmxoHTNOCGqxpF9SbdRAO4OmMXTYzO4FlnmGgHec3FUxv+VeTYbxE+JgcKzVbGbz8Ta5CzLp4yUx5f3mKkI9btxoFAs24MJir7MlP0k/TEg/YcwHEEOKNayIBeUDwmaV+TUgqGKt5PPCv4YyZByQADOT1SFUPSA/Aga8rvL/nQNPC4VFLw6hSdvDpQ4qdCLVk6Lq+y1cD7uCu8+NRd9CS4Hhxv4lHfW8h+NhVXL2hD3zYMalLYCXs/SOdMdcSKYJL+toZ4YMDLouwzdbf9SoHjoK3f6oIPXi3yGCqpPXb2+bT7oq/F1N2ChPfU8aO1hufnpxOmNbir2Xmern622ozmuEeG0jqT5Auwg7HuA6cz1j4ZvC/vitG/PGVegaEXnZ0Phx+sjlGoLBPnQPGMMS0tXNmsIZCaEIQL2x4KleeVJV52TTcRMVHUsaCqBB8hrG0gLC4fkax8HYcjwOEq9Fqay3tB0z/dbR8rflZd3A0FdEU+EmVk6hZUhreXEyxkcfGP3SRA="
